// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh8TLYGiUbrVt_d8Dwo2x76g_AVxTqAQg',
    appId: '1:948684708885:web:48336501d1eadb5729421c',
    messagingSenderId: '948684708885',
    projectId: 'coding-club-38164',
    authDomain: 'coding-club-38164.firebaseapp.com',
    storageBucket: 'coding-club-38164.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDONpsqllnXURMbvPAxJSLNWAY56TtO9ps',
    appId: '1:948684708885:android:0ec99fe38b8f53dd29421c',
    messagingSenderId: '948684708885',
    projectId: 'coding-club-38164',
    storageBucket: 'coding-club-38164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5vuFtKSJedUiTE_HshIQ93ntrlCg6lw4',
    appId: '1:948684708885:ios:c89e26b15e4c5ab329421c',
    messagingSenderId: '948684708885',
    projectId: 'coding-club-38164',
    storageBucket: 'coding-club-38164.appspot.com',
    iosBundleId: 'com.example.codingClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5vuFtKSJedUiTE_HshIQ93ntrlCg6lw4',
    appId: '1:948684708885:ios:6ec2e5a46fc9c1e329421c',
    messagingSenderId: '948684708885',
    projectId: 'coding-club-38164',
    storageBucket: 'coding-club-38164.appspot.com',
    iosBundleId: 'com.example.codingClub.RunnerTests',
  );
}
